package com.poco.PoCoRuntime;

/**
 * Represents a PoCo policy (i.e. one that does not define policy trees). Code generated by compiler will
 * create subclasses of Policy with constructors that configure the root execution object.
 */
public abstract class Policy extends EventResponder implements Queryable, Matchable {
    protected AbstractExecution rootExecution;

    public AbstractExecution getRootExecution() {
        return rootExecution;
    }

    public void setRootExecution(AbstractExecution rootExecution) {
        this.rootExecution = rootExecution;
    }

    @Override
    public boolean accepts(Event event) {
        return rootExecution.accepts(event);
    }

    @Override
    public SRE query(Event event) {
        return rootExecution.query(event);
    }

	@Override
	public String toString() {
		return "Policy [rootExecution=" + rootExecution + "]";
	}
    
    
}
